import Head from 'next/head'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className=''>
          Home
        </main>

        <footer className='text-center'>
            Powered by blank
        </footer>
      </div>
    </Layout>
  )
}
